openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/PatrikTrestik/DiasendAPI/1.0.0
  - description: Diasend API
    url: https://api.diasend.com/1/
info:
  version: "1.0.0"
  title: Diasend API documentation
  description: >-
    This is documentation of known API endpoints, not official documentation provided by API owner.
security:
  - password:
      - PATIENT DIASEND_MOBILE_DEVICE_DATA_RW
paths:
  /patient/data#:
    get:
      summary: Read patient data summary
      description: >-
        Patient data. List of devices.
      operationId: GetPatientSummary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PatientData'
  /patient/data:
    get:
      summary: Read patient data summary
      description: >-
        Patient data. List of devices and its data.
        For glucose reading you have to specifi 'type' and 'date_from', 'date_to'
      operationId: GetPatientData
      parameters:
        - in: query
          name: type
          schema:
            type: string
            enum: [cgm,combined,standardday,score_card,bg_pie_chart,cgm_pie_chart,insulin_pie_chart]
        - in: query
          name: only_cgm
          schema:
            type: boolean
        - in: query
          name: date_from
          schema: 
            type: string
            format: date-time
        - in: query
          name: date_to
          schema: 
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DataItem'
    post:
      summary: Upload data
      description: >-
        Upload patient data. Data itself is encoded in 'payload'
      operationId: PostPatientData
      requestBody:
        required: true
        content:
          application/json:
            schema: 
               $ref: '#/components/schemas/DataUpload'
      responses:
        '200':
          description: OK
components:
  schemas: 
    DataUpload:
      type: object
      properties:
        device_type:
          type: string
        uuid:
          type: string
        pcode:
          type: string
        password:
          type: string
        insulin_brand:
          type: string
        pen_serial:
          type: string
        payload:
          type: string
    DataItem:
      type: object
      properties:
        type: 
          type: string
          enum: [glucose]
        created_at:
          type: string
          format: date-time
        value: 
          type: number
        unit:
          type: string
          enum: [mmol/l]
        flags:
          type: array
          items:
            type: object
            properties:
              flag:
                type: number
              description:
                type: string
    PatientData:
      type: object
      properties:
        data: 
          type: array
          items: 
            $ref: '#/components/schemas/DataItem'
        device: 
          type: object
          properties:
            serial:
              type: string
            manufacturer: 
              type: string
            model: 
              type: string
            first_value_at:
              type: string
              format: date-time
            last_value_at:
              type: string
              format: date-time
            supports_glucose: 
              type: string
            supports_cgm: 
              type: string
            supports_insulin: 
              type: string
            supports_carb: 
              type: string
  securitySchemes:
    password:
      type: oauth2
      flows:
        password:
          tokenUrl: 'oauth2/token'
          scopes:
            PATIENT DIASEND_MOBILE_DEVICE_DATA_RW: allows modifying resources